### PR TITLE
PHP8 сompatibiltiy

### PR DESCRIPTION
**Pull request by sivaschenko**
## Overview
PHP8 сompatibiltiy

## Technical Changes
Dropped support of PHP 7.1 and 7.2
Updated composer.json to allow PHP 8
Updated tests to support PHPUnit 9
Added PHP 8 to Travis builds

### CODE REVIEW

**Comment by sebastianwos** [comment]
Hi!
Do you know when it expected to be merged to master ?

**Comment by eduard13** [comment]
The tests have been fixed after updating the `guzzlehttp/guzzle` to the latest version.
image

**Comment by eduard13** [comment]
### Technical Changes

- Updated the `guzzlehttp/guzzle` to the latest version and adjusted the tests accordingly
- Updated the `phpunit/phpunit` to `9.5.8` and adjusted the `phpunit.xml.dist` accordingly to warnings
- Removed the PHP 7.1 and 7.2 support

**Comment by sivaschenko** [comment]
@chfabbro the pull request is ready for merge. Would you be able to process it?

**Pull request merged**
